# -*- coding: utf-8 -*-
"""Untitled80.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qg83bhLEvEKIFM4lJ1cGMnwmQWBTIBpU
"""

from calendar import *
year = int(input('Enter the Year: '))
print(calendar(year, 2, 1, 8, 3))