# -*- coding: utf-8 -*-
"""Untitled72.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXSe3mhRXIZkqguSaifrb2JC_kkKjhXP
"""

def immunized_position(obligation, yield_annually, years_to_maturity_1, years_to_maturity_2):
  """
  Calculates the values of A and B in the immunized position.

  Args:
    obligation: The amount of the obligation.
    yield_annually: The annual effective yield.
    years_to_maturity_1: The number of years to maturity of the first bond.
    years_to_maturity_2: The number of years to maturity of the second bond.

  Returns:
    A: The value of the investment in the first bond.
    B: The value of the investment in the second bond.
  """

  present_value_obligation = obligation / (1 + yield_annually)**(years_to_maturity_1 + years_to_maturity_2)
  A = present_value_obligation * (1 + yield_annually)**(-years_to_maturity_1)
  B = present_value_obligation - A

  # Print the value of present_value_obligation
  print("Present Value of Obligation = $", present_value_obligation)

  return A, B


obligation = 10000
yield_annually = 0.06
years_to_maturity_1 = 2
years_to_maturity_2 = 10

A, B = immunized_position(obligation, yield_annually, years_to_maturity_1, years_to_maturity_2)

print("A = $", A)
print("B = $", B)

