# -*- coding: utf-8 -*-
"""Untitled91.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ep59EQsSwSI2XoDlnJ22wP-_WU5u4loo
"""

import nc
import datetime

# Define your variables
date_value = datetime.datetime(2023, 9, 27, 0, 0, 0)
shift = 'A'
shift_time = 'DAY'
emp_no1 = 'AF0692'
emp_no2 = 'AF0245'
plant = 'ST3'
barcode_id = '1594808'
side = 'L'
press_no = '5'
order_no = 'N2309260010'
release_no = '*'
sequence_no = '*'

# Create a dictionary with your variables
attributes = {
    'DATE': date_value.strftime('%Y-%m-%d-%H.%M.%S'),
    'SHIFT': shift,
    'SHIFT_TIME': shift_time,
    'EMP_NO1': emp_no1,
    'EMP_NO2': emp_no2,
    'PLANT': plant,
    'BARCODE_ID': barcode_id,
    'SIDE': side,
    'PRESS_NO': press_no,
    'ORDER_NO': order_no,
    'RELEASE_NO': release_no,
    'SEQUENCE_NO': sequence_no
}

# Start the Novacura action
flow = nc.flow(nc, currentMachine, currentStep, form)
p0 = 'START'
p1 = ''
for key, value in attributes.items():
    p1 += f'{key}{chr(31)}{value}{chr(30)}'

# Use Novacura-specific methods or actions to set the language and handle the action
# The code below is illustrative and may need to be adapted to your specific Novacura configuration.

flow.SetLanguage('en')  # Set the language
flow.SomeNovacuraAction(p0, p1)  # Call a Novacura-specific action to handle the task

!pip install msoffcrypto-tool

import pathlib

url = pathlib.Path(r'C:\Users\jay\Desktop\PythonInOffice\remove_excel_password')
excel_files = list(url.glob('*.xlsx'))