# -*- coding: utf-8 -*-
"""Untitled87.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TVb7PvKNIuJJau7UX1AFuOWY8OICKy7O
"""

import pandas as pd

# Replace 'your_excel_file.xlsx' with the actual path to your Excel file
file_path = 'your_excel_file.xlsx'

# Load the Excel file into a DataFrame
df = pd.read_excel(file_path)

# Extract email domains from the 'Email' column (change 'Email' to the actual column name)
email_addresses = df['Email']
email_domains = email_addresses.str.extract(r'@(.+)$')

# Remove duplicates by converting the column to a set and back to a list
unique_domains = list(set(email_domains[0]))

# Print the unique email domains
for domain in unique_domains:
    print(domain)